INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04218', NULL, '李春成', NULL, '《 执法机关公务员职业伦理困境研究——以S机关为例》', '《福建行政学院学报》', '2017.03.10 ', NULL, NULL, '0', '1506');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04218', NULL, '李春成', NULL, '《好干部是怎样炼成的》', '《人民论坛》', '2017.08.25', NULL, NULL, '0', '1505');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04218', NULL, '李春成', NULL, '《 执法机关公务员职业伦理困境研究——以S机关为例》', '《新华文摘杂志社新华文摘网络版》', '2017年11期', NULL, NULL, '0', '1504');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《腐败经历与腐败感知：基于调查实验与直接提问的双重检验》', '《社会》', '2017.6.1', NULL, NULL, '0', '1470');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《Does Oil Cause Ethnic War? Comparing Evidence
from Process-tracing with Quantitative Results》', '《Security Studies》', '2017', NULL, NULL, '0', '2243');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《Location, Location, Location: The Ethno-Geography
of Oil and the Onset of Ethnic War》', '《Chin. Polit. Sci. Rev. (2017》', '2017', NULL, NULL, '0', '2242');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《腐败的两幅面孔：基于7000 个司法裁判文书数据的描述分析》', '《理论与改革》', '2017.9.19', NULL, NULL, '0', '1469');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《“学术腐败”是高等教育面临的大问题》', '《清风》', '2017.5.1', NULL, NULL, '0', '1468');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《在监督下奔跑起来——给一把手们“拉拉袖子”》', '《上海支部生活》', '2016.12下', NULL, NULL, '0', '1467');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09072', NULL, '李辉', NULL, '《还校园净土需尊重“学术规律”》', '《上海支部生活》', '2017.02', NULL, NULL, '0', '1466');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《地方政府间“对口关系”的保障机制》', '《学海》', '2017.4.1', NULL, NULL, '0', '1407');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《地方治理全图景的理论建构——评《理解中国治理的广东样本——广东经验的理论分析》》', '《公共行政评论》', '2017年第6期', NULL, NULL, '0', '1406');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《城市地方政府合并能创造更好的经济绩效吗？——以上海和广州两地为例》', '《复旦城市治理评论第1辑》', '2017.6.1', NULL, NULL, '0', '1405');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《对口合作成于“需要”》', '《社会科学报》', '2017.4.13', NULL, NULL, '0', '1404');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《地方政府间“对口关系”的保障机制》', '《人大复印报刊资料《公共行政系》第10期《学海》（南京），2017.4.54-59》', '2017.10.1', NULL, NULL, '0', '1403');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《东北与东部的“对口合作”如何情投意合？》', '《上观新闻》', '2017.4.12', NULL, NULL, '0', '1402');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《组织侦测危机信号的方法：环境扫描介绍》', '《风险灾害危机研究》', '2016.12.1', NULL, NULL, '0', '1401');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05275', NULL, '李瑞昌', NULL, '《我国应当建立“以风险为中心”的公共安全管理机制》', '《上海政法学院学报》', '2017.1.1', NULL, NULL, '0', '1400');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '33336', NULL, '郦菁', NULL, '《美国保守主义的社会基础和特朗普政权的未来》', '《人大复印报刊资料《国际政治》-《文化纵横》2016.12.52-56》', '2017.4.1', NULL, NULL, '0', '1399');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04840', NULL, '林涓', NULL, '《中国行政区区划通史》', '《复旦大学出版社》', '2017.9.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20514', NULL, '林尚立', NULL, '《当代中国政治基础与发展》', '《中国大百科全书出版社》', '2017.1.1', NULL, NULL, '0', '1306');

INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '06009', NULL, '刘春荣', NULL, '《北极光照耀桃花仑——一个挪威家族的中国情》', '《复旦大学出版社》', '2017.5.1', NULL, NULL, '0', '1285');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '06009', NULL, '刘春荣', NULL, '《Beyond Coercion: The New Politics of Conflict
Processing in China》', '《英文期刊《中国政治学评论》Chinese Political Science Review》', '42787.0', NULL, NULL, '0', '2229');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '06009', NULL, '刘春荣', NULL, '《The new logic of Chinas》', '《Europes World》', '2017', NULL, NULL, '0', '2228');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《政党治理的中国方案——贯彻落实十八届六中全会精神的三重路径》', '《南京社会科学》', '2017.1.1', NULL, NULL, '0', '1243');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《使基层治理动起来：联动网络与中国社区公共物品提供》', '《江苏行政学院学报》', '2017.5.1', NULL, NULL, '0', '1242');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《从“工具主义法律观”到“治理主义法律观”:全面推进依法治国进程中的观念革命》', '《湖北社会科学》', '2017.2.1', NULL, NULL, '0', '1241');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《国家治理与社会发展》', '《国家治理的中国方案[M]//叶南客上海人民出版社》', '2017:3-14.', NULL, NULL, '0', '1240');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《国家治理的中国方案》', '《转型中国的治理研究上海人民出版社.》', '2017:3-47.', NULL, NULL, '0', '1239');

INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《和谐社会构建中的理论与现实问题第一章》', '《山东人民出版社.》', '2017:1-72.', NULL, NULL, '0', '1238');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《社区治理是撬动社会治理的支点》', '《北京日报》', '2017.9.11', NULL, NULL, '0', '1237');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《社区治理怎样从“盆景”到“苗圃”》', '《解放日报》', '2017.3.21', NULL, NULL, '0', '1236');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《[1]嘉定社区营造纪实系列之一--走进嘉定  心就定了》', '《网络媒体》', '2017', NULL, NULL, '0', '1235');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《[2]嘉定社区营造纪实系列之二--嘉定活力：塑造”主人翁社区“》', '《网络媒体》', '2017', NULL, NULL, '0', '1234');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《[3]嘉定社区营造纪实系列之三--机制保障：实现共建共融的社区新篇章》', '《网络媒体》', '2017', NULL, NULL, '0', '1233');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《[4]解剖”全岗通“这只麻雀①│不只是培养班长，而是铸造一个团队》', '《网络媒体》', '2017', NULL, NULL, '0', '1232');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《[5]撬动居民自治的支点》', '《网络媒体》', '2017', NULL, NULL, '0', '1231');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '40046', NULL, '刘建军', NULL, '《[6]社会大转型：从”单位中国“到”社区中国“》', '《网络媒体》', '2017', NULL, NULL, '0', '1230');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31081', NULL, '刘淑华', NULL, '《地方政府危机治理政策传播与信息交互行为研究——基于大数据分析的视角》', '《公共行政评论》', '2017.2.15', NULL, NULL, '0', '-1');

INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31081', NULL, '刘淑华', NULL, '《数据分析视角下的地方政府危机治理与政策传播研究》', '《复旦公共行政评论16辑》', '2017.8.31', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31081', NULL, '刘淑华', NULL, '《《复旦公共行政评论》专刊，编前语》', '《复旦公共行政评论16辑》', '2017.8.31', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31081', NULL, '刘淑华', NULL, '《数据能力与国家治理学术论坛会议综述》', '《复旦公共行政评论16辑》', '2017.8.31', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31081', NULL, '刘淑华', NULL, '《《复旦公共行政评论》专刊，《数据治理与政府能力》》', '《复旦公共行政评论总第16期》', '2017第一期', NULL, NULL, '0', '-5');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《UNLIKELY PARTNERS?》', '《palgravve》', '2017', NULL, NULL, '0', '2208');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《国内规范、国际规范与中欧规范互动》', '《欧洲研究》', '2017.1.1', NULL, NULL, '0', '1191');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《例外论与中美战略思维的差异性》', '《美国研究》', '2017.2.1', NULL, NULL, '0', '1190');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《中国人与美国人思维方式的差异及其对构建“中美新型大国关系”的寓意》', '《当代亚太》', '2017.4.1', NULL, NULL, '0', '1189');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《例外论与中美战略思维的差异性》', '《中国社会科学文摘《美国研究》2017年2期》', '2017.10.1', NULL, NULL, '0', '1188');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《人类命运共同体理论对西方国际关系理论的扬弃》', '《浙江学刊》', '2017.4.1', NULL, NULL, '0', '1187');

INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《中国与欧洲：两种不同的规范性力量》', '《“一带一路”与欧洲 时事出版社》', '2017.3.1', NULL, NULL, '0', '1186');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《中欧在主权和人权上的规范偏好》', '《武汉科技大学学报(社会科学版)》', '2017.6.1', NULL, NULL, '0', '1185');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《国家行为的合理性与国家间互动的对弈逻辑》', '《国际关系研究》', '2017.6.1', NULL, NULL, '0', '1184');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《中国人与美国人思维方式的差异及其对构建“中美新型大国关系”的寓意》', '《复印报刊资料《中国外交》》', '2017.12.1', NULL, NULL, '0', '1183');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《国内规范、国际规范与中欧规范互动》', '《人大复印报刊资料《中国外交》-《欧洲研究》2017.1.18》', '2017.6.1', NULL, NULL, '0', '1182');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05232', NULL, '潘忠岐', NULL, '《广义国际规则的形成、创新与变革》', '《人大复印报刊资料《国际政治》-《国际关系研究》2016.5.3-23》', '2017年第1期', NULL, NULL, '0', '1181');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '07116', NULL, '秦倩', NULL, '《宗教非政府组织的国际法律地位》', '《基督教学术（第十六辑）》', '2016.12.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '07116', NULL, '秦倩', NULL, '《停滞的对话？——世界银行和宗教非政府组织之合作困境》', '《宗教与美国社会（第十四辑）》', '2017.4.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '07116', NULL, '秦倩', NULL, '《南极：地缘政治与国家权益》', '《时事出版社》', '2017.1.1', NULL, NULL, '0', '-3');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '07116', NULL, '秦倩', NULL, '《国际法治与全球治理》', '《复旦国际关系评论21辑》', '2017.12.1', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '07116', NULL, '秦倩', NULL, '《传统医药与国际法》', '《中医药文化》', '2017年第3期', NULL, NULL, '0', '-5');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '07116', NULL, '秦倩', NULL, '《宗教非政府组织在中国：实践与法律》', '《上海人民出版社》', '2017.7.1', NULL, NULL, '0', '-6');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20531', NULL, '邱柏生', NULL, '《关于世界观表现形式的若干问题辨析》', '《思想理论教育》', '2017.9.1', NULL, NULL, '0', '1109');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20531', NULL, '邱柏生', NULL, '《新形势下高校辅导员队伍建设的老议题和新意境》', '《高校辅导员》', '2017.2.1', NULL, NULL, '0', '1108');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20531', NULL, '邱柏生', NULL, '《新形势下高校辅导员队伍建设的老议题和新意境》', '《人大复印报刊资料《思想政治教育》-《高校辅导员》2017.2.3-7》', '2017.8.1', NULL, NULL, '0', '1107');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04018', NULL, '任军锋', NULL, '《帝国的兴衰 修昔底德的正值世界》', '《生活 读书 新知 三联书店》', '2017.11.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04018', NULL, '任军锋', NULL, '《分裂的国家与美利坚人的乡愁——读阿莉霍奇切尔德《本土的陌生人：美国右翼的愤怒与哀伤》》', '《学海》', '2017.5.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04018', NULL, '任军锋', NULL, '《贵族、民主自由：道德哲学家托克维尔》', '《西方政治哲学史 中国人民大学出版社》', '2017.3.1', NULL, NULL, '0', '-3');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04018', NULL, '任军锋', NULL, '《德谟克拉西vs.德谟克拉东——民主的两种政治史路向》', '《政治与法律评论（第八辑）》', '2017.6.1', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《论全面深化改革之图、谱、度、路的辩证统一》', '《新华文摘》', '2017年第2期全文转载', NULL, NULL, '0', '1066');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《关于政治学的主题与政治学基本问题的思考》', '《政治学研究》', '2017.10.1', NULL, NULL, '0', '1065');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《论制度成熟：价值、品相、路径》', '《上海行政学院学报》', '2017年第3期', NULL, NULL, '0', '1064');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《政治认同是如何形成的?》', '《复旦学报（社会科学版）》', '2017年第4期', NULL, NULL, '0', '1063');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《干部选任：关键环节及其关键问题》', '《探索与争鸣》', '2017年第11期', NULL, NULL, '0', '1062');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《从基层民主的发展空间看县政治理的取向》', '《社会科学》', '2017.12.1', NULL, NULL, '0', '1061');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《从政府内部预算走向公共预算——筑牢法治、参与和技术的“三角基石”》', '《中共中央党校学报》', '2017年第5期', NULL, NULL, '0', '1060');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《努力培育价值制度行为相统一的党内政治文化》', '《学习时报》', '2017.7.21', NULL, NULL, '0', '1059');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《通过程序优化与技术改进完善人大制度》', '《新华文摘》', '2017年第4期论点摘编', NULL, NULL, '0', '1058');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《从政治学博士论文看我国政治学研究之取向》', '《新华文摘》', '2017年第7期网络版全文转载', NULL, NULL, '0', '1057');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《推进全面从严治党的制度化进程》', '《新华日报》', '2017.11.15', NULL, NULL, '0', '1056');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《担负起生产思想和理论的责任和使命》', '《文汇报》', '2017.4.7', NULL, NULL, '0', '1055');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《知识能力都不缺，干部还要补点啥》', '《解放日报》', '2017.5.2', NULL, NULL, '0', '1054');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《建构有效的权责体系,防止“责任虚化”》', '《人民论坛》', '2017年第8期', NULL, NULL, '0', '1053');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04376', NULL, '桑玉成', NULL, '《政治认同是如何形成的?》', '《新华文摘》', '2017年第21期论点摘编', NULL, NULL, '0', '1052');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《践行网信事业历史使命，向网络强国大步前进》', '《光明日报 理论版》', '2017.4.14', NULL, NULL, '0', '986');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《武器级勒索软件催生全球网络空间防扩散机制建设契机》', '《信息安全通信保密》', '2017.9.1', NULL, NULL, '0', '985');

INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《美国互联网自由战略的实践与阶段性评估——以2016年美国总统选举与俄罗斯黑客攻击为例》', '《信息安全与通信保密》', '2017.4.10', NULL, NULL, '0', '984');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《从2016年美国大选看美式民主的困境》', '《《光明日报》2016.10.26-人大书报资料中心《马克思主义文摘》》', '2017.1.1', NULL, NULL, '0', '983');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《特朗普时期美国国家网络安全战略调整及其影响》', '《中国信息安全》', '2017.10.15', NULL, NULL, '0', '982');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《武器级勒索软件攻击考验国家网络安全能力》', '《中国信息安全》', '2017.7.15', NULL, NULL, '0', '981');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05278', NULL, '沈逸', NULL, '《迈向新时期的中美关系》', '《党政干部参考》', '2017.12上', NULL, NULL, '0', '980');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《互联互通世界的治理和秩序》', '《世界经济与政治》', '2017.2.1', NULL, NULL, '0', '871');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《准确把握中国制度精神》', '《学习时报》', '2017.4.26', NULL, NULL, '0', '870');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《充分认识当今世界格局的新变化》', '《人民日报》', '2017.1.7', NULL, NULL, '0', '869');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《辨证看待资本主义的系统性危机》', '《人民日报》', '2017.1.22', NULL, NULL, '0', '868');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《正确认识和使用合法性概念》', '《光明日报》', '2017.1.23', NULL, NULL, '0', '867');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《为世界和平与发展作出新的重大贡献》', '《人民日报》', '2017-11-05', NULL, NULL, '0', '866');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《不断推进社会主义协商民主》', '《求是》', '2017年第11期', NULL, NULL, '0', '865');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《习近平新时代中国特色社会主义思想的实践意义》', '《新华日报》', '2017-11-22', NULL, NULL, '0', '864');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《中国哲学社科研究和教育的国际化目标》', '《神州学人》', '2017.1.4', NULL, NULL, '0', '863');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '31555', NULL, '苏长和', NULL, '《准确把握中国制度精神》', '《领导科学》', '2017.6.1', NULL, NULL, '0', '862');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36017', NULL, '孙小逸', NULL, '《Spontaneous Cognitive Liberation in the Context of Rights-defending Actions: A Case Study of the Evolution of Homeowner Activists’ Rights Consciousness》', '《 Chinese Journal of Sociology》', '2017', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36017', NULL, '孙小逸', NULL, '《Dynamic political opportunities and environmental forces linking up: A case study of anti-PX contention in Kunming”, Journal of Contemporary China, 2017》', '《Journal of Contemporary China》', '2017', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36017', NULL, '孙小逸', NULL, '《社交媒体与城市治理的多元互动模式——以广州城管与摊贩的冲突为例》', '《复旦城市治理评论第1期复旦大学出版社》', '2017.6.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36017', NULL, '孙小逸', NULL, '《城市社区治理：上海的经验》', '《上海人民出版社》', '2017.12.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《Return entrepreneurs: bind and impact. Book review of Entrepreneurship and Talent Management from a Global Perspective: Global Returnees》', '《Science and Public Policy》', '2017', NULL, NULL, '0', '-1');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《创新型城市的基础科研发展评估：基于深圳的实证分析》', '《公共行政评论》', '2017第6期', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《信息计量在科技创新政策研究中的应用现状局限与前景!》', '《科学学研究》', '2017.2.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《中国科研成果的引用增长是否存在“俱乐部效应”？》', '《人大书报资料中心《创新政策与管理》，财经研究，2016.12》', '2017.3.1', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《深圳科研发展可视化分析：Y1980-Y2015》', '《《2016年度广东创新驱动发展蓝皮书》，书章，296-340，中山大学国家治理研究院出版.》', '2017', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《Experiences of Returned Chinese Migrants in Higher Education Examined through a Case Study》', '《 in Rethinking international skilled migration edited by Micheline van Riemsdijk & Qingfang Wang, Routledge. ISBN 1138918725. 》', '2017', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '36020', NULL, '唐莉', NULL, '《The Penalty of containing more non-English articles. Scientometrics》', '《Scientometrics》', '2017', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《《SGI 框架下欧盟公共服务一体化的价值基础建构及其推进策略》》', '《《中国行政管理》》', '2017年第2期', NULL, NULL, '0', '772');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《《使命-责任体制：中国共产党新型政治形态建构论纲》》', '《南京社会科学》', '2017年第7期', NULL, NULL, '0', '771');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《当代中国财政权的控权机制设计及其实现路径》', '《中共中央党校学报》', '2017.10.1', NULL, NULL, '0', '770');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《从党建国体制到党治国体制再到党兴国体制：中国共产党治国理政新型体制的建构》', '《行政论坛》', '2017.5.1', NULL, NULL, '0', '769');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《当代中国文化治理的生成逻辑与维度建构》', '《中国文化产业评论第24卷 上海人民出版社》', '2017.7.1', NULL, NULL, '0', '768');

INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《《绘就蓝图治天下：中国共产党治国济世之道》》', '《人民日报理论版》', '2017.6.25', NULL, NULL, '0', '767');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《上海基本公共服务的清单化和标准化》', '《科学发展》', '2017.10.1', NULL, NULL, '0', '766');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《使命-责任体制：中国共产党新型政治形态建构论纲》', '《党政干部参考》', '2017.7.1', NULL, NULL, '0', '765');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《权责清单制度：建构现代政府的中国方案》', '《人大书报资料中心《学术界》2016.12转载》', '2017.4.1', NULL, NULL, '0', '764');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《研究郡县制需要重视的三大制度性背景和原则》', '《华东理工大学学报》', '2017.5.1', NULL, NULL, '0', '763');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《《中国特色社会主义的六个重大论断》》', '《北京日报》', '2017.814', NULL, NULL, '0', '762');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《世界城市群与大都市治理》', '《复旦城市治理评论第1辑》', '2017.6.1', NULL, NULL, '0', '761');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《城市公共服务创新研究》', '《复旦城市治理评论第2辑》', '2017.12.1', NULL, NULL, '0', '760');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《《应对公共危机:构建全球化时代具有强领导力的责任政府》》', '《中国党政干部论坛》', '2017年第5期', NULL, NULL, '0', '759');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09006', NULL, '唐亚林', NULL, '《探寻城市治理秘密 创造美好城市生活》', '《复旦城市治理评论第1辑》', '2017.6.1', NULL, NULL, '0', '758');


INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《Social Class and Voter Turnout in China Local Congress Elections and Citizen-Regime Relations 》', '《Political Research Quarterly》', 'vol. 70, 2: pp. 243-256. , First Published February 13, 2017.', NULL, NULL, '0', '2166');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《Chapter 14 Political Participation in East Asia, In Tun-jen Cheng and Yun-han Chu (eds.) Routledge Handbook of Democratization in East Asia (11 Sept 2017).(程同仁、朱云汉 等著 《劳特里奇东亚民主化研究手册》,第14章 “东亚的政治参与”251-268 页)》', '《》', '(11 Sept 2017).', NULL, NULL, '0', '2165');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《中国崛起背景下的亚洲多边主义——如何构建新的亚洲认同》', '《文化纵横》', '2017.10.10', NULL, NULL, '0', '769');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《互联网使用对政治机构信任的影响研究》', '《经济社会体制比较》', '2017 第一期，164-177.', NULL, NULL, '0', '768');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《西方国家元首的权威从哪来》', '《人民论坛》', '2017,(01):26-27.', NULL, NULL, '0', '767');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《中国民航的国际化战略》', '《中国新闻周刊》', '2017年（11）39', NULL, NULL, '0', '766');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《“两个一百年”伟大目标的历史维度》', '《21世纪经济报道》', '2017、10/27，第4版', NULL, NULL, '0', '765');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《中国崛起 亚洲故事》', '《联合早报》', '2017/5/17 第08页', NULL, NULL, '0', '764');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《中国如何引领亚洲世纪 》', '《中国新闻周刊》', '017、11.13 第42期 第45页', NULL, NULL, '0', '763');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《塑造亚洲认同 引领亚洲世纪》', '《环球时报》', '2017年11月17日 第14版', NULL, NULL, '0', '762');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《方瑞丰试论以供给侧改革促进中国民航业的国际化发展 》', '《中国民航报 》', '2017/9/28  第7版', NULL, NULL, '0', '761');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35184', NULL, '王正绪', NULL, '《两个“十五年”战略安排的重大意义》', '《人民论坛》', '2017.11.15', NULL, NULL, '0', '760');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《Citizenship education as NGO intervention:turning migrant children in Shanghai into "new citizens"》', '《Citizenship Studies》', 'Published online 17Jul 2017', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《“城市规模的政治学：为什么超大城市的外来人口控制政策难以奏效”, 》', '《华中师范大学学报》', '2017.6.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《Urbanized Children: Rural-urban Awareness and Identity Consciousness of Migrant Workers’ Children》', '《Chinese Education and Society》', 'Vol 50, No 4, 2017.', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《Social Integration of Second-generation Rural Migrants in Shanghai》', '《 In Mingjun Zhang & Xinye Wu(Ed.), Public Security and Governance in Contemporary China, Routledge, 》', '2017, pp 170-188. ', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《Does Oil Cause Ethnic War? Comparing Evidence
from Process-tracing with Quantitative Results》', '《Security Studies》', '2017', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《自负的深刻：社会科学何以洞察人性》', '《探索与争鸣》', '2017.5.1', NULL, NULL, '0', '-2');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09071', NULL, '熊易寒', NULL, '《坚持道路自信　走向民族复兴》', '《文汇报》', '2017.5.3', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《21世纪以来宗教与国际关系研究的发展——徐以骅教授访谈》', '《国际政治研究》', '2017.4.1', NULL, NULL, '0', '624');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《宗教与美国2016年大选》', '《宗教与美国社会（第十四辑）》', '2017.4.1', NULL, NULL, '0', '623');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《从“信仰中国”到“信仰周边”——中国与周边国家的宗教互动》', '《宗教与美国社会第十五辑》', '2017.10.1', NULL, NULL, '0', '622');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《宗教与美国社会（第十四辑）》', '《时事出版社》', '2017.4.1', NULL, NULL, '0', '621');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《宗教与美国社会（第十五辑）》', '《时事出版社》', '2017.10.1', NULL, NULL, '0', '620');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《评宗教与国家安全关联性研究的新著--《后冷战时代的宗教文明与国家安全》》', '《宗教与美国社会第十五辑》', '2017.10.1', NULL, NULL, '0', '619');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《宗教与国家安全 写在“全民国家安全教育日”》', '《中国宗教》', '2017.4.1', NULL, NULL, '0', '618');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《基督教学术（第十六辑）》', '《上海三联书店》', '2016.12.1', NULL, NULL, '0', '617');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《中国基督教神学教育和研究的四次重心转移》', '《天风》', '2017.7.1', NULL, NULL, '0', '616');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20480', NULL, '徐以骅', NULL, '《历史回眸与时代使命：在纪念宗教改革500周年暨基督教中国化研讨会上的主旨发言》', '《天风》', '2017.12.1', NULL, NULL, '0', '615');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20525', NULL, '臧志军', NULL, '《城市环境治理》', '《上海人民出版社》', '2016.12.1', NULL, NULL, '0', '601');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20525', NULL, '臧志军', NULL, '《城市发展模式和市民生活方式的重塑：环境治理的非技术主义路径》', '《城市环境治理-上海人民出版社》', '2016.12.1', NULL, NULL, '0', '600');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20525', NULL, '臧志军', NULL, '《推进共青团和青联界别履职进一步发挥作用的研究》', '《人民政协理论与实践研究》', '2017.8.1', NULL, NULL, '0', '599');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20525', NULL, '臧志军', NULL, '《贿选的成因及其整治》', '《团结》', '2016.12.1', NULL, NULL, '0', '598');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20525', NULL, '臧志军', NULL, '《中日关系：2016——低位徘徊与？变 总论》', '《复旦大学国际问题研究院 专题研究报告 七》', '2017.3.1', NULL, NULL, '0', '597');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '33061', NULL, '张骥', NULL, '《开放的独立外交——2017年法国总统大选与马克龙政府的外交政策》', '《欧洲研究》', '2017年第5期', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '33061', NULL, '张骥', NULL, '《左右法国大选的三个“脱离”》', '《文汇报》', '2017.5.5', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '33061', NULL, '张骥', NULL, '《“一带一路”倡议的中欧对接：双层欧盟的视角》', '《 中国社会科学院国际研究学部集刊 社会科学文献出版社》', '2017.4.1', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '33061', NULL, '张骥', NULL, '《何以交流：中外人文交流的三大源流》', '《世界知识》', '2017年第23期', NULL, NULL, '0', '-4');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '08007', NULL, '张建新', NULL, '《西方国际政治经济学 第一、三、五章》', '《上海人民出版社》', '2017.7.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '08007', NULL, '张建新', NULL, '《中国能源企业国际化的“成长曲线”》', '《上海交通大学学报》', '2017.5.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34121', NULL, '张平', NULL, '《The Impacts of Private Experience on the Employment of Different Public Job Positions》', '《Public Personnel Management》', '2017', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34121', NULL, '张平', NULL, '《房地产税的税率大小和税负分布》', '《学习时报》', '2017.5.26', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34121', NULL, '张平', NULL, '《房地产税：谁该缴？缴多少？》', '《经济学家茶座》', '2017.2.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34121', NULL, '张平', NULL, '《房地产税：设不设减免，怎么免？》', '《学习时报》', '2017.5.19', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34121', NULL, '张平', NULL, '《房地产税：谁该缴，缴多少？》', '《经济学家茶座》', '2017年第2期', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35181', NULL, '赵剑治', NULL, '《公司治理方式能否引入公共领域》', '《解放日报》', '2017.05.16', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35181', NULL, '赵剑治', NULL, '《国务智库报告10辑》', '《》', '2017.12.1', NULL, NULL, '0', '1999');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34019', NULL, '郑冰岛', NULL, '《Household Registration, Urban Status Attainment, and Social Stratification in Contemporary Urban China》', '《Research in Social Stratification and Mobility》', '2017.11.1', NULL, NULL, '0', '2121');


INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《Towards typology of adaptive governance in the digital government context:The role of decision-making and accountability》', '《Government Information Quarterly》', '2017', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《中国地方政府开放数据研究：技术与法律特性》', '《公共行政评论》', '2017.1.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《Mapping government social media research and moving it forward:A framework and a research agenda》', '《Government Information Quarterly》', '2017.6.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《政务微信传播方式与效果研究》', '《电子政务》', '2017.1.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《如何进一步推动公共数据资源的开放》', '《学习时报》', '2017.7.17', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_ywqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《Extending Impact Analysis in Government Social Media Research：Five IIIustrative Cases》', '《》', '2017', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《国外“移动互联网+公共服务”比较研究》', '《智慧城市评论》', '2017第三辑', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《公共数据开放的产出与效果研究——以上海开放数据创新应用大赛为例》', '《电子政务》', '2017年第9期', NULL, NULL, '0', '-5');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《开放政府数据准备度评估：法律法规与政策》', '《电子政务》', '2017年第9期', NULL, NULL, '0', '-6');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '09255', NULL, '郑磊', NULL, '《政府数据开放的潜在风险与对策研究——以上海市为例》', '《电子政务》', '2017年第9期', NULL, NULL, '0', '-7');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35036', NULL, '郑宇', NULL, '《Privatization with ‘vested interests’ in China》', '《Socio-Economic Review (社会经济评论)》', '2017, Vol. 0, No. 0, 1–25', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35036', NULL, '郑宇', NULL, '《援助有效性与新型发展合作模式构想》', '《世界经济与政治》', '2017.8.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《文化生产新空间中的传统文化再加工——对二次元、网上文化社区与弘扬传统文化关系的研究》', '《中国青年研究》', '2017年9期', NULL, NULL, '0', '418');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《重塑城市治理整体性的政党逻辑——国家治理现代化与上海大党建格局发展》', '《中国浦东干部学院学报》', '2017.3.30', NULL, NULL, '0', '417');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《网络重新定义基层：“青年之声”的启示》', '《中国共青团》', '2017.4', NULL, NULL, '0', '416');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《坚持中国特色社会主义法治道路与当代青年使命》', '《中国共青团》', '2017.6.15', NULL, NULL, '0', '415');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《坚定改革信心，强化责任担当 将群团改革进行到底》', '《中国共青团》', '2017年10期', NULL, NULL, '0', '414');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中国共产党在构建人类命运共同体中的担当》', '《当代世界》', '2017年第11期', NULL, NULL, '0', '413');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中国青年发展的政治逻辑--党管青年原则与中国青年发展的关系研究》', '《青年学报》', '2017.11.15', NULL, NULL, '0', '412');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《以有效支持存在:群团基层组织建设的方向》', '《红旗文摘》', '2016年11期', NULL, NULL, '0', '411');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《执政党治理国家应积极适应网络社会发展》', '《人民日报理论观察版的人民观察栏目》', '2017.1.8', NULL, NULL, '0', '410');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《阅读他者，助人认识自己》', '《解放日报-思想周刊/观点》', '2017.8.8', NULL, NULL, '0', '409');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《走好关键一步，开启新的征程》', '《经济日报-理论周刊》', '2017.9.22', NULL, NULL, '0', '408');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《Reaching for Modern Chinese Civilization》', '《中国画报》', '2017.10.12', NULL, NULL, '0', '407');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中国特色社会主义拓展发展中国家走向现代化的途径》', '《贵州民族报》', '2017.10.19', NULL, NULL, '0', '406');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中国奇迹与西方眼中的“中国谜题”》', '《新华社》', '2017.9.27', NULL, NULL, '0', '405');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中共党代会报告首次提出加强“长期执政能力建立”》', '《亚太日报》', '2017.10.20', NULL, NULL, '0', '404');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《十九大将进一步坚定“中国模式” 为人类文明发展带来更多可能性》', '《新华社（采访稿）》', '2017.9.30', NULL, NULL, '0', '403');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《读懂中共执政奥秘》', '《新华社（采访稿）》', '2017.9.22', NULL, NULL, '0', '402');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中共十九大竖起人类发展史的新里程碑》', '《新华社（采访稿）》', '2017.10.24', NULL, NULL, '0', '401');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《外资企业和中共党支部良性互动获得双赢》', '《新华社（采访稿）》', '2017.11.10', NULL, NULL, '0', '400');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《外国政要期待中国共产党与世界政党高层对话会，希望学习反腐经验》', '《南方都市报》', '2017.12.1', NULL, NULL, '0', '399');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《世界政党“朋友圈”的这次高规格聚会，传递出什么重要信息》', '《解放日报》', '2017.12.2', NULL, NULL, '0', '398');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《构建人类命运共同体的政党逻辑已经生成！》', '《人民日报中央厨房》', '2017.12.3', NULL, NULL, '0', '397');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《世界舞台上 中国共产党的作用越来越重要》', '《人民日报中央厨房》', '2017.12.3', NULL, NULL, '0', '396');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《顺应时代潮流 共建美好世界》', '《光明日报》', '2017.12.2', NULL, NULL, '0', '395');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《国家治理体系全面现代化》', '《腾讯网》', '2017.3.5', NULL, NULL, '0', '394');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《“青年之声”的启示--网络重新定义基层》', '《中国青年网》', '2017.3.7', NULL, NULL, '0', '393');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《创新社会参与机制 《规划》为国家发展注入“青年力量”》', '《中国青年网》', '2017.5.8', NULL, NULL, '0', '392');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《为更好认识自己而阅读他者--“三心二意”游英国》', '《中国青年网》', '2017.7.23', NULL, NULL, '0', '391');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《正确工作方法是“将改革进行到底”的重要保证》', '《光明网-理论频道》', '2017.7.24', NULL, NULL, '0', '390');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《党对军队的绝对领导是保证各项事业顺利发展的重要法宝》', '《人民网》', '2017.7.25', NULL, NULL, '0', '389');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《“将改革进行到底”与当代青年发展》', '《中国青年网》', '2017.7.27', NULL, NULL, '0', '388');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《为中国特色社会主义新的发展阶段做好理论与战略的准备》', '《光明网-理论频道》', '2017.7.28', NULL, NULL, '0', '387');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《人民军队是中华民族伟大复兴的坚强守护者》', '《人民网-观点频道》', '2017.7.28', NULL, NULL, '0', '386');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《保卫和平是人民军队的光荣职责》', '《光明网-理论频道》', '2017.7.30', NULL, NULL, '0', '385');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《将群团改革进行到底》', '《光明网-理论频道》', '2017.8.29', NULL, NULL, '0', '384');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《不忘初心、继续前进，勇于全面深化改革》', '《中国青年网》', '2017.10.9', NULL, NULL, '0', '383');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《加强党的长期执政能力建设是实现伟大梦想的新要求》', '《光明网-理论频道（中青网转载）》', '2017.10.27', NULL, NULL, '0', '382');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《在新时代继续坚持全面深化改革》', '《光明网-理论频道》', '2017.11.24', NULL, NULL, '0', '381');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《国家治理现代化应从四个维度适应网络社会发展》', '《冶金企业文化》', '2017.4.20', NULL, NULL, '0', '380');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《中国特色社会主义拓展发展中国家走向现代化的途径（深入学习贯彻习近平同志“7·26”重要讲话精神）》', '《人民日报》', '2017.10.11', NULL, NULL, '0', '379');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '05277', NULL, '郑长忠', NULL, '《城市治理与政党发展的双向建构》', '《中国社会科学报》', '2017.10.19', NULL, NULL, '0', '378');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20524', NULL, '周帆', NULL, '《香港立法会扩权：背景与前景》', '《香港基本法实施20周年研讨会论文集》', '2017.3.18', NULL, NULL, '0', '411');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20524', NULL, '周帆', NULL, '《香港社会运动的政治机遇结构分析》', '《法律研讨会论文集》', '2017.12.8', NULL, NULL, '0', '410');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20524', NULL, '周帆', NULL, '《香港管治的新挑战:港独现象的初步认知纲要》', '《法学研讨会论文集》', '2017.6.1', NULL, NULL, '0', '409');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20524', NULL, '周帆', NULL, '《“尊重两制差异”，完善高度自治》', '《光明网-理论频道　》', '2017.7.5', NULL, NULL, '0', '408');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《专栏导语:土地政策:公共政策研究亟待加强的领域》', '《公共行政评论》', '2017.4.15', NULL, NULL, '0', '332');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《全球资本下的社区治理》', '《格致出版社 上海人民出版社》', '2017.7.1', NULL, NULL, '0', '331');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《政府信任的概念测量、影响因素与提升策略》', '《厦门大学学报》', '2017.5.28', NULL, NULL, '0', '330');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《“政策之窗”的关闭与重启——基于劳教制度终结的经验研究》', '《武汉大学学报(哲学社会科学版)》', '2017.9.1', NULL, NULL, '0', '329');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《电子政务如何影响政府信任?——基于武汉、天津、重庆调研数据的实证研究》', '《南京社会科学》', '2017.5.11', NULL, NULL, '0', '328');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《用制度防范行政决策的“任性”》', '《社会科学报》', '2017.8.10', NULL, NULL, '0', '327');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《信任因素如何影响电子政务公众使用意愿?——对三种机理的实证检验》', '《电子政务》', '2017.6.20', NULL, NULL, '0', '326');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《基于知识图谱的国际电子治理研究回顾及热点透析》', '《电子政务》', '2017.2.20', NULL, NULL, '0', '325');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《反“四风”并不是要减少职工正常福利》', '《人民论坛》', '2017.2.15', NULL, NULL, '0', '324');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '04881', NULL, '朱春奎', NULL, '《官员治理研究进展与展望:基于CSSCI的文献计量与内容分析》', '《地方治理研究》', '2017.1.10', NULL, NULL, '0', '323');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《世界银行反腐败标准对金砖银行制度建设的启示》', '《国际观察》', '2017年第4期', NULL, NULL, '0', '309');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《亚太自贸区建设势头将得以继续》', '《文汇报》', '2017年11月10日', NULL, NULL, '0', '308');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《汉堡峰会围绕三大议题做文章》', '《文汇报》', '2017年7月8日', NULL, NULL, '0', '307');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《从新开发银行看金砖合作与国际制度改革》', '《国际经济合作》', '2017年第8期', NULL, NULL, '0', '306');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《G20汉堡峰会：分歧、化解路径及启示》', '《当代世界》', '2017年第8期', NULL, NULL, '0', '305');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《发展使命与金砖国家合作的动力》', '《对外传播》', '2017年第6期', NULL, NULL, '0', '304');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《G20贸易议题：一根有肉的硬骨头》', '《新民晚报》', '2017年7月8日', NULL, NULL, '0', '303');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《数字经济：如何用好达摩克利斯之剑》', '《新民晚报》', '2017年7月9日', NULL, NULL, '0', '302');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '34010', NULL, '朱杰进', NULL, '《与对手合作：中国与世界银行在筹建亚投行中的合作》', '《复旦国际关系评论第二十辑》', '2017年第1期', NULL, NULL, '0', '301');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《政府职能的三次转变：以权力为中心的改革回归》', '《江苏行政学院学报》', '2017.6.1', NULL, NULL, '0', '246');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《政社分开的基础：领导权与治理权分开》', '《中共福建省委党校学报》', '2017.6.1', NULL, NULL, '0', '245');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《政社分开：从资源依附走向共生性资源依赖》', '《福建行政学院学报》', '2017.4.1', NULL, NULL, '0', '244');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《国家治理现代化与机构改革》', '《人大复印报刊资料《公共行政》-《学术界》2016.11.16-25》', '2017.3.1', NULL, NULL, '0', '243');


INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《政社分开的基础：领导权与治理权分开》', '《人大复印报刊资料《公共行政》-《中共福建省委党校学报》2017.6.4-10》', '2017.9.1', NULL, NULL, '0', '242');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《政社分开：从资源依附走向共生性资源依赖》', '《复印报刊资料《公共行政》》', '2017.11.1', NULL, NULL, '0', '241');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '20523', NULL, '竺乾威', NULL, '《国家治理现代化对领导能力的挑战》', '《北京日报》', '2017.5.8', NULL, NULL, '0', '240');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35056', NULL, '左才', NULL, '《政治学研究中的因果关系：四种不同的理解视角》', '《国外理论动态》', '2017.1.1', NULL, NULL, '0', '-1');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35056', NULL, '左才', NULL, '《地方领导干部激励机制的运作与绩效》', '《学海》', '2017.3.1', NULL, NULL, '0', '-2');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35056', NULL, '左才', NULL, '《政治学案例分析方法中的争论与共识》', '《复旦政治学评论第十七辑》', '2016.12.1', NULL, NULL, '0', '-3');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35056', NULL, '左才', NULL, '《社会绩效、一票否决与官员晋升———来自中国城市的证据》', '《公共管理与政策评论　》', '2017.6.1', NULL, NULL, '0', '-4');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35056', NULL, '左才', NULL, '《干部激励机制与地方治理：治理目标优先序的调整及地区差异的实证研究》', '《转型中国的治理研究，复旦大学社会科学高等研究院转型中国研究丛书》', ' 2017年，第241-265页', NULL, NULL, '0', '-5');
INSERT INTO `fudan_research_paper_zwqk` (`ID`, `employee_ID`, `ISI_number`, `name`, `rank`, `subject`, `journal`, `year`, `head`, `end`, `hidden`, `px`) VALUES (NULL, '35056', NULL, '左才', NULL, '《政治学研究方法的权衡与发展》', '《复旦大学出版社》', '2017.9.1', NULL, NULL, '0', '-6');
